### ISSUE TITLE
Doesn't "Secret Teams" kinda imply that players don't know their actual team?

### ISSUE THREAD

**Issue by ghost** [LeonTG77/KillReveal#1]
Everything after [this line](https://github.com/LeonTG77/KillReveal/blob/8fef67eae302fe1037d96b32a191fadc9352603f/src/com/leontg77/killreveal/cmds/RandomCommand.java#L47) seems to be copied from some sort of team manager you wrote a while ago, and you're messaging players what team they're on & what their teammates are.

I'm too tired for a PR (been awake since 17 hours...) and I'd probably break something in the process seeing how differently you design plugins, so here's Your Friendly Nudge™.

For reference, [here](https://redd.it/3oqrhz) is the original scenario post.

**Comment by LeonTG** [comment]
It's secret for others but the players on the team itself should know, the faketeam class is so it doesn't sort tab after teams
